"""add row information in product

Revision ID: 3208c1378164
Revises: 5e5920767470
Create Date: 2024-02-08 03:24:00.138150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3208c1378164'
down_revision: Union[str, None] = '5e5920767470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('information', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'product', ['information'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'information')
    # ### end Alembic commands ###
